---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu-systemd:22.04
    dockerfile: Dockerfile
    pre_build_image: false
#    command: "/usr/sbin/init"
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
